name: Aviso-UNINTER
run-name: ${{ github.actor }} - UNINTER

on:
  workflow_dispatch:
#  schedule:
#    - cron: '30 5,21 * * *'

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: check conteudo do repositorio
        uses: actions/checkout@v3

      - name: instalando python
        uses: actions/setup-python@v4
        with:
         python-version: '3.12.0'

      - name: instalar os pacotes do requirements.txt
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip install -r requirements.txt

      - name: edit .env file
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          UNINTER_LOGIN: ${{ secrets.UNINTER_LOGIN }}
          UNINTER_PASSWORD: ${{ secrets.UNINTER_PASSWORD }}
        run: |
          touch .env
          echo EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }} >> .env
          echo EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} >> .env
          echo UNINTER_LOGIN=${{ secrets.UNINTER_LOGIN }} >> .env
          echo UNINTER_PASSWORD=${{ secrets.UNINTER_PASSWORD }} >> .env

      - name: executar arquivo principal
        run: python main.py

      - name: apagando arquivo .env
        run: rm .env
